### ISSUE TITLE
Requirements out of date.

### ISSUE THREAD

**Issue by josarsepi** [byt3smith/CIRTKit#1]
http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz#egg=pefile no longer works.

**Comment by burdenless** [comment]
Thanks @josarsepi, I will update that soon

**Comment by burdenless** [comment]
Updated requirements

**Comment by q2dg** [comment]
Well...it seems what is out of date is CIRTKit, sadly.

**Comment by burdenless** [comment]
Yes @q2dg, CIRTKit has not been actively maintained for a while, unfortunately. There was a lot more I wanted to do with it, but have had other projects to maintain
